MODULE PROFILE
    IMPLICIT NONE
    
    !MESH INFO
    INTEGER, SAVE :: N1, N2, N3
    REAL, SAVE :: LX, LY, LZ
    REAL, PARAMETER :: PI = 3.141592653589793
    REAL, SAVE :: RE
    
    !STATISTICS OPTIONS
    !AVERAGE FIELD
    LOGICAL, SAVE :: VEL_AVERAGE(3)
    
    !VORTICITY FIELD
    LOGICAL, SAVE :: VOR_CALC
    LOGICAL, SAVE :: VOR_AVERAGE(3)
    
    !IO PATH
    CHARACTER(LEN = 128), SAVE :: MESH_PATH, DATA_PATH, PROFILE_PATH
    CHARACTER(LEN = 128), SAVE :: OUTPUT_PATH
    
    !TOTAL NUM
    INTEGER, SAVE :: START_NUM, END_NUM, STEP
    CONTAINS
    
    SUBROUTINE READ_PROFILE()
        IMPLICIT NONE
        
        N1 = 128
        N2 = 128
        N3 = 128
        RE = 5600
        LX = 4 * PI
        LY = 2
        LZ = 2 * PI
        START_NUM = 0
        END_NUM = 99900
        STEP = 1000
        
        MESH_PATH = 'E:\steady\CHANNEL.GRD'
        DATA_PATH = 'F:\data3300\'
        !DATA_PATH = 'E:\MOVE\'
        !OUTPUT_PATH = 'E:\MOVEPOST\'
        OUTPUT_PATH = 'H:\post_nc\'
        
    END SUBROUTINE READ_PROFILE
    
END MODULE PROFILE