MODULE PROFILE
    IMPLICIT NONE
    
    !MESH INFO
    INTEGER, SAVE :: N1, N2, N3
    REAL, SAVE :: LX, LY, LZ
    
    !STATISTICS OPTIONS
    !AVERAGE FIELD
    LOGICAL, SAVE :: VEL_AVERAGE(3)
    
    !VORTICITY FIELD
    LOGICAL, SAVE :: VOR_CALC
    LOGICAL, SAVE :: VOR_AVERAGE(3)
    
    !IO PATH
    CHARACTER(LEN = 128), SAVE :: MESH_PATH, DATA_PATH, PROFILE_PATH
    CHARACTER(LEN = 128), SAVE :: OUTPUT_PATH
    
    CONTAINS
    
    SUBROUTINE READ_PROFILE()
        IMPLICIT NONE
        
    END SUBROUTINE READ_PROFILE
    
END MODULE PROFILE