MODULE PROFILE
    IMPLICIT NONE
    
    !STATISTICS OPTIONS
    !AVERAGE FIELD
    LOGICAL, SAVE :: VEL_AVERAGE(3)
    INTEGER, SAVE, ALLOCATABLE :: VEL_AVE_POS(:, :)
    
    !VORTICITY FIELD
    LOGICAL, SAVE :: VOR_CALC
    LOGICAL, SAVE :: VOR_AVERAGE(3)
    INTEGER, SAVE, ALLOCATABLE :: VOR_AVE_POS(:, :)
    
END MODULE PROFILE